title: Lovisa # your name (or website title) here
logo: "/images/IMG_0167.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Student at STI
  <br><br>
 
  <a href="https://www.linkedin.com/in/lovisa-jonsson-995205194">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
